name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  npm_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: |
          npm -v
          npm ci

  npm_test:
    runs-on: ubuntu-latest
    needs: [ npm_ci ]
    steps:
      - run: npm test

  npm_build:
    runs-on: ubuntu-latest
    needs: [ npm_ci ]
    steps:
      - run: |
          tsc -v
          npm run build
